# Generated by Django 2.2.4 on 2020-10-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travel_start', models.DateField()),
                ('travel_end', models.DateField()),
                ('plan', models.CharField(max_length=255)),
                ('favorites', models.ManyToManyField(related_name='travelFav', to='ExamApp.User')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelUploader', to='ExamApp.User')),
            ],
        ),
    ]
